<?php

/**
 * List Items Calculator to import
 *
 * @see https://docs.google.com/spreadsheets/d/1Q6r9d4JGp1FAdbK-Uihooshp7WFsoO0B-CIXuwbnQ4o/edit#gid=1830119977
 */
return array(
    "2-door_wardrobe" => ["en" => "2-door wardrobe","fr"=>"Armoire 2 portes","nl"=>"Garderobekast met 2 deuren","area_m2"=>"1.25","volume_m3"=>"3.7"],
    "4-door_wardrobe" => ["en" => "4-door wardrobe","fr"=>"Armoire 4 portes","nl"=>"Garderobekast met 4 deuren","area_m2"=>"2.4","volume_m3"=>"7.3"],
    "ac_unit" => ["en" => "AC unit","fr"=>"Air conditonné portable","nl"=>"Airconditioning toestel","area_m2"=>"","volume_m3"=>"0.3"],
    "adult_bicycle" => ["en" => "Adult's bicycle","fr"=>"Vélo adulte","nl"=>"Volwassenenfiets","area_m2"=>"0.3","volume_m3"=>"0.85"],
    "american_fridge" => ["en" => "American fridge","fr"=>"Frigo américain","nl"=>"Amerikaanse koelkast","area_m2"=>"0.7","volume_m3"=>"2.1"],
    "archive_box" => ["en" => "Archive box","fr"=>"Boite archive","nl"=>"Archief doos","area_m2"=>"0.05","volume_m3"=>"0.1"],
    "armchair" => ["en" => "Armchair","fr"=>"Fauteuil","nl"=>"Fauteuil","area_m2"=>"0.45","volume_m3"=>"1.35"],
    "artificial_plant" => ["en" => "Artificial plant","fr"=>"Plante artificielle","nl"=>"Kunstplant","area_m2"=>"0.2","volume_m3"=>"0.5"],
    "baby_bath" => ["en" => "Baby bath","fr"=>"Baignoire bébé","nl"=>"Babybadje","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "bar_stool" => ["en" => "Bar stool","fr"=>"Tabouret de bar","nl"=>"Barkruk","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "bedside_table" => ["en" => "Bedside table","fr"=>"Table de chevet","nl"=>"Nachtkastje","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "bin" => ["en" => "Bin","fr"=>"Poubelle","nl"=>"Vuilnisbak","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "bin2" => ["en" => "Bin","fr"=>"Poubelle","nl"=>"Vuilnisbak","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "bookcase" => ["en" => "Bookcase","fr"=>"Bibliothèque","nl"=>"Boekenkast","area_m2"=>"0.3","volume_m3"=>"0.85"],
    "bookcase2" => ["en" => "Bookcase","fr"=>"Bibliothèque","nl"=>"Boekenkast","area_m2"=>"0.3","volume_m3"=>"0.85"],
    "bookcase3" => ["en" => "Bookcase","fr"=>"Bibliothèque","nl"=>"Boekenkast","area_m2"=>"0.3","volume_m3"=>"0.85"],
    "boxify_box" => ["en" => "Boxify Box","fr"=>"Boite Boxify","nl"=>"Boxify-doos","area_m2"=>"","volume_m3"=>"0.1"],
    "breakfast_table_(4_seater)" => ["en" => "Breakfast table (4 seater)","fr"=>"Table 4 places","nl"=>"Tafel","area_m2"=>"","volume_m3"=>"1"],
    "bunk_bed" => ["en" => "Bunk bed","fr"=>"Lits superposés","nl"=>"Stapelbed","area_m2"=>"1.45","volume_m3"=>"4.3"],
    "chair" => ["en" => "Chair","fr"=>"Chaise de bureau","nl"=>"Stoel","area_m2"=>"0.15","volume_m3"=>"0.45"],
    "chaise_longue" => ["en" => "Chaise longue","fr"=>"Méridienne","nl"=>"Chaise longue","area_m2"=>"0.75","volume_m3"=>"2.2"],
    "changing_table" => ["en" => "Changing table","fr"=>"Table à langer","nl"=>"Commode","area_m2"=>"0.2","volume_m3"=>"0.55"],
    "chest_of_drawers" => ["en" => "Chest of drawers","fr"=>"Commode","nl"=>"Ladekast","area_m2"=>"0.2","volume_m3"=>"0.5"],
    "chest_of_drawers2" => ["en" => "Chest of drawers","fr"=>"Commode (3 tiroirs)","nl"=>"Ladekast","area_m2"=>"0.3","volume_m3"=>"0.95"],
    "children_bed" => ["en" => "Children's bed","fr"=>"Lit enfant","nl"=>"Kinderbed","area_m2"=>"0.4","volume_m3"=>"1.2"],
    "children_chair" => ["en" => "Children's chair","fr"=>"Chaise enfant","nl"=>"Kinderstoel","area_m2"=>"0.5","volume_m3"=>"0.1"],
    "children_table" => ["en" => "Children's table","fr"=>"Table enfant","nl"=>"Kindertafel","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "children_wardrobe" => ["en" => "Children's wardrobe","fr"=>"Armoire","nl"=>"Garderobekast","area_m2"=>"0.3","volume_m3"=>"0.95"],
    "coffee_table" => ["en" => "Coffee table","fr"=>"Table basse","nl"=>"Salontafel","area_m2"=>"0.3","volume_m3"=>"0.8"],
    "corner_sofa" => ["en" => "Corner sofa","fr"=>"Canapé modulaire","nl"=>"Modulaire zitbank","area_m2"=>"1.5","volume_m3"=>"4.5"],
    "cot" => ["en" => "Cot","fr"=>"Lit bébé","nl"=>"Babybedje","area_m2"=>"0.3","volume_m3"=>"0.9"],
    "desk" => ["en" => "Desk","fr"=>"Bureau","nl"=>"Bureau","area_m2"=>"0.2","volume_m3"=>"0.6"],
    "desk2" => ["en" => "Desk","fr"=>"Bureau","nl"=>"Bureau","area_m2"=>"0.3","volume_m3"=>"0.9"],
    "dining_chair" => ["en" => "Dining chair","fr"=>"Chaise","nl"=>"Stoel","area_m2"=>"0.2","volume_m3"=>"0.6"],
    "dining_table" => ["en" => "Dining table","fr"=>"Table 6 places","nl"=>"Tafel","area_m2"=>"0.5","volume_m3"=>"1.5"],
    "dish_washer" => ["en" => "Dish washer","fr"=>"Lave-vaiselle","nl"=>"Vaatwasser","area_m2"=>"0.2","volume_m3"=>"0.65"],
    "display_cabinet" => ["en" => "Display cabinet","fr"=>"Vitrine","nl"=>"Vitrinekast","area_m2"=>"0.8","volume_m3"=>"2.3"],
    "double_bed" => ["en" => "Double bed","fr"=>"Lit double","nl"=>"2-persoonsbed","area_m2"=>"0.9","volume_m3"=>"2.65"],
    "double_mattress" => ["en" => "Double mattress","fr"=>"Matelas double","nl"=>"2-persoonsmatras","area_m2"=>"0.45","volume_m3"=>"1.3"],
    "dresser_6_drawers" => ["en" => "Dresser (6 drawers)","fr"=>"Commode (6 tiroirs)","nl"=>"Ladekast (6 laden)","area_m2"=>"","volume_m3"=>"1.41"],
    "dressing_table" => ["en" => "Dressing table","fr"=>"Coiffeuse","nl"=>"Toilettafel","area_m2"=>"0.4","volume_m3"=>"1.25"],
    "drying_rack" => ["en" => "Drying rack","fr"=>"Séchoir à linge","nl"=>"Droogrek","area_m2"=>"0.1","volume_m3"=>"0.4"],
    "filing_cabinet" => ["en" => "Filing cabinet","fr"=>"Bloc tiroirs","nl"=>"Archiefkast","area_m2"=>"0.2","volume_m3"=>"0.5"],
    "floor_lamp" => ["en" => "Floor lamp","fr"=>"Lampe suir pied","nl"=>"Staande lamp","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "floor_lamp2" => ["en" => "Floor lamp","fr"=>"Lampadaire","nl"=>"Staande lamp","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "footstool" => ["en" => "Footstool","fr"=>"Repose-pieds","nl"=>"Voetenbank","area_m2"=>"0.1","volume_m3"=>"0.25"],
    "freezer" => ["en" => "Freezer","fr"=>"Congélateur","nl"=>"Diepvrieskoffer","area_m2"=>"0.55","volume_m3"=>"1.6"],
    "fridge" => ["en" => "Fridge","fr"=>"Réfrigérateur","nl"=>"1-deurkoelkast","area_m2"=>"0.35","volume_m3"=>"1"],
    "fridge_with_freezer" => ["en" => "Fridge with freezer","fr"=>"Combi frigo-congélateur","nl"=>"Koelkast met diepvriezer","area_m2"=>"0.4","volume_m3"=>"1.3"],
    "garden_bench" => ["en" => "Garden bench","fr"=>"Parasol","nl"=>"Parasol","area_m2"=>"0.1","volume_m3"=>"0.4"],
    "garden_bencj" => ["en" => "Garden bencj","fr"=>"Banc de jardin","nl"=>"Bank","area_m2"=>"0.5","volume_m3"=>"1.6"],
    "garden_chair" => ["en" => "Garden chair","fr"=>"Chaise de jardin","nl"=>"Tuinstoel","area_m2"=>"0.3","volume_m3"=>"0.9"],
    "garden_heater" => ["en" => "Garden heater","fr"=>"Chauffage de jardin","nl"=>"Tuin gasverwarming","area_m2"=>"","volume_m3"=>"1"],
    "garden_table" => ["en" => "Garden table","fr"=>"Table de jardin","nl"=>"Tafel","area_m2"=>"0.8","volume_m3"=>"2.3"],
    "garden_tools" => ["en" => "Garden tools","fr"=>"Outils de jardin","nl"=>"Tuingereedschap","area_m2"=>"0.15","volume_m3"=>"0.4"],
    "golf_club" => ["en" => "Golf club","fr"=>"Club de golf","nl"=>"Golfclub","area_m2"=>"","volume_m3"=>"0.3"],
    "headboard" => ["en" => "Headboard","fr"=>"Tête de lit","nl"=>"Voorschot","area_m2"=>"","volume_m3"=>"0.5"],
    "highchair" => ["en" => "Highchair","fr"=>"Chaise haute","nl"=>"Hoge kinderstoel","area_m2"=>"0.2","volume_m3"=>"0.5"],
    "Ironing_board" => ["en" => "Ironing board","fr"=>"Table à repasser","nl"=>"Strijkplank","area_m2"=>"0.1","volume_m3"=>"0.25"],
    "kid_bicycle" => ["en" => "Kid's bicycle","fr"=>"Vélo enfant","nl"=>"Kinderfiets","area_m2"=>"","volume_m3"=>"0.55"],
    "ladder" => ["en" => "Ladder","fr"=>"Échelle","nl"=>"Ladder","area_m2"=>"0.1","volume_m3"=>"0.4"],
    "lamp_table" => ["en" => "Lamp table","fr"=>"Lampe","nl"=>"Lamp","area_m2"=>"","volume_m3"=>"0.15"],
    "large_file_cabinet" => ["en" => "Large file cabinet","fr"=>"Armoire pour dossier","nl"=>"Grote archiefkast","area_m2"=>"0.65","volume_m3"=>"1.9"],
    "laundry_basket" => ["en" => "Laundry basket","fr"=>"Panier à linge","nl"=>"Wasmand","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "lawn_mower" => ["en" => "Lawn mower","fr"=>"Tondeuse à gazon","nl"=>"Grasmaaier","area_m2"=>"0.2","volume_m3"=>"0.6"],
    "linen_rack" => ["en" => "Linen rack","fr"=>"Étagère","nl"=>"Stellingkast","area_m2"=>"0.3","volume_m3"=>"0.9"],
    "microwave" => ["en" => "Microwave","fr"=>"Micro-ondes","nl"=>"Microgolfoven","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "minifridge" => ["en" => "Mini fridge","fr"=>"Mini frigo (mini bar)","nl"=>"Kleine Koelkast","area_m2"=>"","volume_m3"=>"0.15"],
    "mirror" => ["en" => "Mirror","fr"=>"Miroir","nl"=>"Spiegel","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "moving_box_large" => ["en" => "Moving box large","fr"=>"Carton large","nl"=>"Verhuisdoos large","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "moving_box_medium" => ["en" => "Moving box medium","fr"=>"Carton medium","nl"=>"Verhuisdoos medium","area_m2"=>"0.075","volume_m3"=>"0.15"],
    "moving_box_small" => ["en" => "Moving box small","fr"=>"Carton small","nl"=>"Verhuisfoos small","area_m2"=>"0.05","volume_m3"=>"0.1"],
    "office_chair" => ["en" => "Office chair","fr"=>"Chaise de bureau","nl"=>"Bureaustoel","area_m2"=>"0.3","volume_m3"=>"0.85"],
    "outdoor_grill" => ["en" => "Outdoor grill","fr"=>"Barbecue","nl"=>"Barbecue","area_m2"=>"0.15","volume_m3"=>"0.4"],
    "oven" => ["en" => "Oven","fr"=>"Cuisinière","nl"=>"Fornuis","area_m2"=>"0.2","volume_m3"=>"0.65"],
    "paper_bin" => ["en" => "Paper bin","fr"=>"Poubelle","nl"=>"Vuilnisbak","area_m2"=>"0.05","volume_m3"=>"0.1"],
    "piano" => ["en" => "Piano","fr"=>"Piano","nl"=>"Piano","area_m2"=>"1.1","volume_m3"=>"3.3"],
    "picture_frame" => ["en" => "Picture frame","fr"=>"Tableau","nl"=>"Lijst","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "picture_frame2" => ["en" => "Picture frame","fr"=>"Tableau","nl"=>"Lijst","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "picture_frame3" => ["en" => "Picture frame","fr"=>"Tableau","nl"=>"Lijst","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "rug" => ["en" => "Rug","fr"=>"Tapis","nl"=>"Vloerkleed","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "rug2" => ["en" => "Rug","fr"=>"Tapis","nl"=>"Vloerkleed","area_m2"=>"0.2","volume_m3"=>"0.7"],
    "rug3" => ["en" => "Rug","fr"=>"Tapis","nl"=>"Vloerkleed","area_m2"=>"0.2","volume_m3"=>"0.7"],
    "shelving_unit" => ["en" => "Shelving unit","fr"=>"Étagère","nl"=>"Open kast","area_m2"=>"0.7","volume_m3"=>"2"],
    "shoe_rack" => ["en" => "Shoe rack","fr"=>"Étagère à chaussures","nl"=>"Schoenenrek","area_m2"=>"0.15","volume_m3"=>"0.45"],
    "side_table" => ["en" => "Side table","fr"=>"Table d'appoint","nl"=>"Tafeltje","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "sideboard" => ["en" => "Sideboard","fr"=>"Buffet","nl"=>"Buffet","area_m2"=>"0.4","volume_m3"=>"1.25"],
    "single_bed" => ["en" => "Single bed","fr"=>"Lit simple","nl"=>"1-persoonsbed","area_m2"=>"0.8","volume_m3"=>"2.3"],
    "single_mattress" => ["en" => "Single mattress","fr"=>"Matelas simple","nl"=>"1-persoonsmatras","area_m2"=>"0.3","volume_m3"=>"0.8"],
    "ski" => ["en" => "Ski","fr"=>"Ski","nl"=>"Ski","area_m2"=>"","volume_m3"=>"0.1"],
    "snowboard" => ["en" => "Snowboard","fr"=>"Snowboard","nl"=>"Snowboard","area_m2"=>"","volume_m3"=>"0.25"],
    "sofa_2_seater" => ["en" => "Sofa (2 seater)","fr"=>"Canapé 2 places","nl"=>"Zitsbank (2)","area_m2"=>"0.85","volume_m3"=>"2.5"],
    "sofa_3_seater" => ["en" => "Sofa (3 seater)","fr"=>"Canapé 3 places","nl"=>"Zitsbank (3)","area_m2"=>"1","volume_m3"=>"3.05"],
    "stool" => ["en" => "Stool","fr"=>"Tabouret","nl"=>"Kruk","area_m2"=>"0.5","volume_m3"=>"0.1"],
    "suitcase" => ["en" => "Suitcase","fr"=>"Valise","nl"=>"Koffer","area_m2"=>"0.1","volume_m3"=>"0.4"],
    "surfboard" => ["en" => "Surfboard","fr"=>"Planche de surf","nl"=>"Surfplank","area_m2"=>"","volume_m3"=>"0.25"],
    "tea_cart" => ["en" => "Tea cart","fr"=>"Désserte","nl"=>"Dientafeltje","area_m2"=>"","volume_m3"=>"0.5"],
    "toolbox" => ["en" => "Toolbox","fr"=>"Boite à outils","nl"=>"Gereedschapskist","area_m2"=>"0.1","volume_m3"=>"0.2"],
    "toy_box" => ["en" => "Toy box","fr"=>"Coffre à jouets","nl"=>"Speelgoedkist","area_m2"=>"0.1","volume_m3"=>"0.3"],
    "trolley" => ["en" => "Trolley","fr"=>"Trolley","nl"=>"Trolley","area_m2"=>"","volume_m3"=>"0.2"],
    "tumble_dryer" => ["en" => "Tumble dryer","fr"=>"Sèche-linge","nl"=>"Droogkast","area_m2"=>"0.2","volume_m3"=>"0.65"],
    "tv_" => ["en" => "TV ","fr"=>"Télévision","nl"=>"Televisie","area_m2"=>"0.2","volume_m3"=>"0.55"],
    "tv_bench" => ["en" => "TV bench","fr"=>"Banc TV","nl"=>"TV-meubel","area_m2"=>"0.2","volume_m3"=>"0.65"],
    "tv_cabinet" => ["en" => "TV cabinet","fr"=>"Meuble TV","nl"=>"TV-opbergcombi","area_m2"=>"1.1","volume_m3"=>"3.2"],
    "tyre" => ["en" => "Tyre","fr"=>"Pneu","nl"=>"Band","area_m2"=>"","volume_m3"=>"0.6"],
    "vacuum_cleaner" => ["en" => "Vacuum cleaner","fr"=>"Aspirateur","nl"=>"Stofzuiger","area_m2"=>"0.05","volume_m3"=>"0.15"],
    "wardobe_box" => ["en" => "Wardrobe box","fr"=>"Penderie","nl"=>"Boxify-kledingdoos","area_m2"=>"","volume_m3"=>"0.3"],
    "washing_machine" => ["en" => "Washing machine","fr"=>"Lave-linge","nl"=>"Wasmachine","area_m2"=>"0.2","volume_m3"=>"0.65"],
    "workbench" => ["en" => "Workbench","fr"=>"Etabli","nl"=>"Werkbank","area_m2"=>"0.4","volume_m3"=>"1.1"],
);
